version: '3.8'

services:
  frontend:
    build:
      context: ../frontend
      dockerfile: ../server-setup/frontend.dockerfile
    volumes:
      - frontend-build:/app/dist
    networks:
      - uvcs-network

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    volumes:
      - frontend-build:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      frontend:
        condition: service_completed_successfully
      backend:
        condition: service_healthy
    networks:
      - uvcs-network

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: uvcs
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - uvcs-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  backend:
    build:
      context: ../backend
      dockerfile: ../server-setup/backend.dockerfile
    environment:
      - DB_TYPE=postgres
      - DB_HOST=postgres
      - DB_PORT=5432
      - POSTGRES_DB=uvcs
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - GIN_MODE=release
      - PORT=8080
    volumes:
      - uvcs-data:/app/data
    expose:
      - "8080"
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:8080/api/health || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - uvcs-network

networks:
  uvcs-network:
    driver: bridge

volumes:
  uvcs-data:
    driver: local
  frontend-build:
  postgres-data: 